begin
  require 'jasmine'

  load 'tasks/jasmine.rake'
  load 'jasmine/tasks/jasmine.rake'
rescue LoadError
  task :jasmine do
    abort "Jasmine is not available. In order to run jasmine, you must: (sudo) gem install jasmine"
  end
end

desc "Run Cucumber features"
task :cucumber do
  exec "node_modules/.bin/cucumber.js"
end
